/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/common/ActionBar.vue')['default']
    BackupSelect: typeof import('./src/components/common/BackupSelect.vue')['default']
    BarLineChart: typeof import('./src/components/common/charts/BarLineChart.vue')['default']
    Calculator: typeof import('./src/components/common/Calculator.vue')['default']
    CalendarGrid: typeof import('./src/components/common/CalendarGrid.vue')['default']
    PieChart: typeof import('./src/components/common/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
    TransactionItem: typeof import('./src/components/mobile/TransactionItem.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
  }
}
