/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/common/ActionBar.vue')['default']
    BackupSelect: typeof import('./src/components/common/BackupSelect.vue')['default']
    BarLineChart: typeof import('./src/components/common/charts/BarLineChart.vue')['default']
    Calculator: typeof import('./src/components/common/Calculator.vue')['default']
    CalendarGrid: typeof import('./src/components/common/CalendarGrid.vue')['default']
    DesktopSidebar: typeof import('./src/components/desktop/DesktopSidebar.vue')['default']
    EditTransactionModal: typeof import('./src/components/desktop/EditTransactionModal.vue')['default']
    EntryPanel: typeof import('./src/components/common/EntryPanel.vue')['default']
    GroupedTransactionList: typeof import('./src/components/desktop/GroupedTransactionList.vue')['default']
    MonthYearPicker: typeof import('./src/components/desktop/MonthYearPicker.vue')['default']
    PieChart: typeof import('./src/components/common/charts/PieChart.vue')['default']
    ReportsPanel: typeof import('./src/components/common/ReportsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/common/SettingsPanel.vue')['default']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
    TransactionItem: typeof import('./src/components/desktop/TransactionItem.vue')['default']
    TransactionList: typeof import('./src/components/desktop/TransactionList.vue')['default']
  }
}
